export const site = {
  name: "MNR Petrol",
  url: "https://mnrpetrol.com",
  locale: "tr_TR",
  description:
    "MNR Petrol olarak Borax, Oilport, Xenol, Brava, Japanoil ve Skynell markalarıyla motor yağları, antifriz, fren hidrolik sıvıları, katkı maddeleri ve endüstriyel ürünler sunuyoruz.",
  keywords: [
    "mnr petrol",
    "motor yağı",
    "motor yağları",
    "antifriz",
    "fren hidrolik sıvısı",
    "katkı maddeleri",
    "endüstriyel yağlar",
    "hidrolik yağ",
    "borax",
    "oilport",
    "xenol",
    "brava",
    "japanoil",
    "skynell",
  ],
  phone: "+90 532 562 71 23",
  legalName: "MNR Petrol Tarım İnş. San. Tic. Ltd. Şti.",
  tagline: "Antalya Madeni Yağ",
  address: {
    street: "Uncalı Mh. Şehit Teğmen Abdulkadir Güler Cad. Bilgi Sitesi",
    district: "Konyaaltı",
    city: "Antalya",
    country: "TR",
    lat: 36.8629,
    lng: 30.6556,
  },
  brand: {
    red: "#D71920",
    dark: "#1A1A1A",
  },
  hours: "Mo-Sa 09:00-18:00",
} as const;
